# syntax=docker/dockerfile:1
#
ARG IMAGEBASE=frommakefile
#
FROM ${IMAGEBASE}
#
ENV \
    CGO_ENABLED=0 \
    GOARCH=riscv64 \
    GOOS=linux \
    GOPATH=/go \
    GOTOOLCHAIN=local
#
RUN set -xe \
    && (if [ ! -e /etc/nsswitch.conf ]; then echo 'hosts: files dns' > /etc/nsswitch.conf; fi) \
    && apk add --no-cache --purge -uU \
        ca-certificates \
        libc-dev \
        go \
        go-doc \
        git \
    && mkdir -p \
        ${GOPATH}/bin \
        ${GOPATH}/pkg \
        ${GOPATH}/src \
    && chown -R ${S6_USER:-alpine} ${GOPATH} \
    && chmod -R 1777 ${GOPATH} \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
ENV \
    GOBIN=${GOPATH}/bin \
    GOCACHE=${GOPATH}/.cache \
    GOENV=${GOPATH}/env \
    GOMODCACHE=${GOPATH}/pkg/mod \
    PATH=${GOPATH}/bin:${PATH}
#
ENTRYPOINT ["/usershell"]
#
CMD ["go", "version"]
