#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

# S6_GO_PACKAGES=""; # list of packages passed at runtime, if required
# must be main packages else go issues warning
if [ -n "${S6_GO_PACKAGES}" ]; then
    vecho "Installing GO packages: ${S6_GO_PACKAGES}";
    cd ${GOPATH} \
    && s6-setuidgid \
        $(ls -ldn . | awk 'NR==1 {print $3":"$4}') \
        go install ${S6_GO_PACKAGES};
fi;
