#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

GOPATH="${GOPATH:-/go}";
# GO_PROJECTDIR="${GO_PROJECTDIR:-/project}";
# projectdir should be in full path and outside of $GOPATH

# setup deps tree from go.mod
if [ -z "${S6_GO_SKIP_GET}" ] \
&& [ -n "${GO_PROJECTDIR}" ] \
&& [ "${GO_PROJECTDIR}" != "${GOPATH}*" ] \
&& [ -f "${GO_PROJECTDIR}/go.mod" ];
then
    vecho "Getting GO dependecies from: ${GO_PROJECTDIR}/go.mod";
    cd ${GO_PROJECTDIR} \
    && s6-setuidgid \
        $(ls -ldn . | awk 'NR==1 {print $3":"$4}') \
        go get ./...;
fi;

